<?php

namespace Tests\Query\Schema;

use PHPUnit\Framework\TestCase;
use Tests\Query\AssertsBindingCount;
use Utopia\Query\Builder\PostgreSQL as PgBuilder;
use Utopia\Query\Query;
use Utopia\Query\Schema\Blueprint;
use Utopia\Query\Schema\Feature\ForeignKeys;
use Utopia\Query\Schema\Feature\Procedures;
use Utopia\Query\Schema\Feature\Triggers;
use Utopia\Query\Schema\PostgreSQL as Schema;

class PostgreSQLTest extends TestCase
{
    use AssertsBindingCount;
    // Feature interfaces

    public function testImplementsForeignKeys(): void
    {
        $this->assertInstanceOf(ForeignKeys::class, new Schema());
    }

    public function testImplementsProcedures(): void
    {
        $this->assertInstanceOf(Procedures::class, new Schema());
    }

    public function testImplementsTriggers(): void
    {
        $this->assertInstanceOf(Triggers::class, new Schema());
    }

    // CREATE TABLE — PostgreSQL types

    public function testCreateTableBasic(): void
    {
        $schema = new Schema();
        $result = $schema->create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name', 255);
            $table->string('email', 255)->unique();
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('"id" BIGINT', $result->query);
        $this->assertStringContainsString('GENERATED BY DEFAULT AS IDENTITY', $result->query);
        $this->assertStringContainsString('"name" VARCHAR(255)', $result->query);
        $this->assertStringContainsString('PRIMARY KEY ("id")', $result->query);
        $this->assertStringContainsString('UNIQUE ("email")', $result->query);
    }

    public function testCreateTableColumnTypes(): void
    {
        $schema = new Schema();
        $result = $schema->create('test_types', function (Blueprint $table) {
            $table->integer('int_col');
            $table->bigInteger('big_col');
            $table->float('float_col');
            $table->boolean('bool_col');
            $table->text('text_col');
            $table->datetime('dt_col', 3);
            $table->timestamp('ts_col', 6);
            $table->json('json_col');
            $table->binary('bin_col');
            $table->enum('status', ['active', 'inactive']);
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('INTEGER NOT NULL', $result->query);
        $this->assertStringContainsString('BIGINT NOT NULL', $result->query);
        $this->assertStringContainsString('DOUBLE PRECISION NOT NULL', $result->query);
        $this->assertStringContainsString('BOOLEAN NOT NULL', $result->query);
        $this->assertStringContainsString('TEXT NOT NULL', $result->query);
        $this->assertStringContainsString('TIMESTAMP(3) NOT NULL', $result->query);
        $this->assertStringContainsString('TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL', $result->query);
        $this->assertStringContainsString('JSONB NOT NULL', $result->query);
        $this->assertStringContainsString('BYTEA NOT NULL', $result->query);
        $this->assertStringContainsString("CHECK (\"status\" IN ('active', 'inactive'))", $result->query);
    }

    public function testCreateTableSpatialTypes(): void
    {
        $schema = new Schema();
        $result = $schema->create('locations', function (Blueprint $table) {
            $table->id();
            $table->point('coords', 4326);
            $table->linestring('path');
            $table->polygon('area');
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('GEOMETRY(POINT, 4326)', $result->query);
        $this->assertStringContainsString('GEOMETRY(LINESTRING, 4326)', $result->query);
        $this->assertStringContainsString('GEOMETRY(POLYGON, 4326)', $result->query);
    }

    public function testCreateTableVectorType(): void
    {
        $schema = new Schema();
        $result = $schema->create('embeddings', function (Blueprint $table) {
            $table->id();
            $table->vector('embedding', 128);
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('VECTOR(128)', $result->query);
    }

    public function testCreateTableUnsignedIgnored(): void
    {
        $schema = new Schema();
        $result = $schema->create('t', function (Blueprint $table) {
            $table->integer('age')->unsigned();
        });
        $this->assertBindingCount($result);

        // PostgreSQL doesn't support UNSIGNED
        $this->assertStringNotContainsString('UNSIGNED', $result->query);
        $this->assertStringContainsString('INTEGER NOT NULL', $result->query);
    }

    public function testCreateTableNoInlineComment(): void
    {
        $schema = new Schema();
        $result = $schema->create('t', function (Blueprint $table) {
            $table->string('name')->comment('User display name');
        });
        $this->assertBindingCount($result);

        // PostgreSQL doesn't use inline COMMENT
        $this->assertStringNotContainsString('COMMENT', $result->query);
    }
    // AUTO INCREMENT

    public function testAutoIncrementUsesIdentity(): void
    {
        $schema = new Schema();
        $result = $schema->create('t', function (Blueprint $table) {
            $table->id();
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('GENERATED BY DEFAULT AS IDENTITY', $result->query);
        $this->assertStringNotContainsString('AUTO_INCREMENT', $result->query);
    }
    // DROP INDEX — no ON table

    public function testDropIndexNoOnTable(): void
    {
        $schema = new Schema();
        $result = $schema->dropIndex('users', 'idx_email');

        $this->assertEquals('DROP INDEX "idx_email"', $result->query);
    }
    // CREATE INDEX — USING method + operator class

    public function testCreateIndexWithGin(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('documents', 'idx_content_gin', ['content'], method: 'gin', operatorClass: 'gin_trgm_ops');

        $this->assertEquals(
            'CREATE INDEX "idx_content_gin" ON "documents" USING GIN ("content" gin_trgm_ops)',
            $result->query
        );
    }

    public function testCreateIndexWithHnsw(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('embeddings', 'idx_embedding_hnsw', ['embedding'], method: 'hnsw', operatorClass: 'vector_cosine_ops');

        $this->assertEquals(
            'CREATE INDEX "idx_embedding_hnsw" ON "embeddings" USING HNSW ("embedding" vector_cosine_ops)',
            $result->query
        );
    }

    public function testCreateIndexWithGist(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('locations', 'idx_coords_gist', ['coords'], method: 'gist');

        $this->assertEquals(
            'CREATE INDEX "idx_coords_gist" ON "locations" USING GIST ("coords")',
            $result->query
        );
    }
    // PROCEDURES — CREATE FUNCTION

    public function testCreateProcedureUsesFunction(): void
    {
        $schema = new Schema();
        $result = $schema->createProcedure(
            'update_stats',
            params: [['IN', 'user_id', 'INT'], ['OUT', 'total', 'INT']],
            body: 'SELECT COUNT(*) INTO total FROM orders WHERE orders.user_id = user_id;'
        );

        $this->assertStringContainsString('CREATE FUNCTION "update_stats"', $result->query);
        $this->assertStringContainsString('LANGUAGE plpgsql', $result->query);
        $this->assertStringNotContainsString('CREATE PROCEDURE', $result->query);
    }

    public function testDropProcedureUsesFunction(): void
    {
        $schema = new Schema();
        $result = $schema->dropProcedure('update_stats');

        $this->assertEquals('DROP FUNCTION "update_stats"', $result->query);
    }
    // TRIGGERS — EXECUTE FUNCTION

    public function testCreateTriggerUsesExecuteFunction(): void
    {
        $schema = new Schema();
        $result = $schema->createTrigger(
            'trg_updated_at',
            'users',
            timing: 'BEFORE',
            event: 'UPDATE',
            body: 'NEW.updated_at = NOW();'
        );

        $this->assertStringContainsString('EXECUTE FUNCTION', $result->query);
        $this->assertStringContainsString('CREATE TRIGGER "trg_updated_at"', $result->query);
        $this->assertStringNotContainsString('BEGIN SET', $result->query);
    }
    // FOREIGN KEY — DROP CONSTRAINT

    public function testDropForeignKeyUsesConstraint(): void
    {
        $schema = new Schema();
        $result = $schema->dropForeignKey('orders', 'fk_user');

        $this->assertEquals(
            'ALTER TABLE "orders" DROP CONSTRAINT "fk_user"',
            $result->query
        );
    }
    // ALTER — PostgreSQL specifics

    public function testAlterModifyUsesAlterColumn(): void
    {
        $schema = new Schema();
        $result = $schema->alter('users', function (Blueprint $table) {
            $table->modifyColumn('name', 'string', 500);
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('ALTER COLUMN "name" TYPE VARCHAR(500)', $result->query);
    }

    public function testAlterAddIndexUsesCreateIndex(): void
    {
        $schema = new Schema();
        $result = $schema->alter('users', function (Blueprint $table) {
            $table->addIndex('idx_email', ['email']);
        });
        $this->assertBindingCount($result);

        $this->assertStringNotContainsString('ADD INDEX', $result->query);
        $this->assertStringContainsString('CREATE INDEX "idx_email" ON "users" ("email")', $result->query);
    }

    public function testAlterDropIndexIsStandalone(): void
    {
        $schema = new Schema();
        $result = $schema->alter('users', function (Blueprint $table) {
            $table->dropIndex('idx_email');
        });
        $this->assertBindingCount($result);

        $this->assertEquals('DROP INDEX "idx_email"', $result->query);
    }

    public function testAlterColumnAndIndexSeparateStatements(): void
    {
        $schema = new Schema();
        $result = $schema->alter('users', function (Blueprint $table) {
            $table->addColumn('score', 'integer');
            $table->addIndex('idx_score', ['score']);
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('ALTER TABLE "users" ADD COLUMN', $result->query);
        $this->assertStringContainsString('; CREATE INDEX "idx_score" ON "users" ("score")', $result->query);
    }

    public function testAlterDropForeignKeyUsesConstraint(): void
    {
        $schema = new Schema();
        $result = $schema->alter('orders', function (Blueprint $table) {
            $table->dropForeignKey('fk_old');
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('DROP CONSTRAINT "fk_old"', $result->query);
    }
    // EXTENSIONS

    public function testCreateExtension(): void
    {
        $schema = new Schema();
        $result = $schema->createExtension('vector');

        $this->assertEquals('CREATE EXTENSION IF NOT EXISTS "vector"', $result->query);
    }

    public function testDropExtension(): void
    {
        $schema = new Schema();
        $result = $schema->dropExtension('vector');

        $this->assertEquals('DROP EXTENSION IF EXISTS "vector"', $result->query);
    }
    // Views — double-quote wrapping

    public function testCreateView(): void
    {
        $schema = new Schema();
        $builder = (new PgBuilder())->from('users')->filter([Query::equal('active', [true])]);
        $result = $schema->createView('active_users', $builder);

        $this->assertEquals(
            'CREATE VIEW "active_users" AS SELECT * FROM "users" WHERE "active" IN (?)',
            $result->query
        );
    }

    public function testDropView(): void
    {
        $schema = new Schema();
        $result = $schema->dropView('active_users');

        $this->assertEquals('DROP VIEW "active_users"', $result->query);
    }
    // Shared operations — still work with double quotes

    public function testDropTable(): void
    {
        $schema = new Schema();
        $result = $schema->drop('users');
        $this->assertBindingCount($result);

        $this->assertEquals('DROP TABLE "users"', $result->query);
    }

    public function testTruncateTable(): void
    {
        $schema = new Schema();
        $result = $schema->truncate('users');
        $this->assertBindingCount($result);

        $this->assertEquals('TRUNCATE TABLE "users"', $result->query);
    }

    public function testRenameTableUsesAlterTable(): void
    {
        $schema = new Schema();
        $result = $schema->rename('users', 'members');
        $this->assertBindingCount($result);

        $this->assertEquals('ALTER TABLE "users" RENAME TO "members"', $result->query);
    }

    // Edge cases

    public function testDropIfExists(): void
    {
        $schema = new Schema();
        $result = $schema->dropIfExists('users');

        $this->assertEquals('DROP TABLE IF EXISTS "users"', $result->query);
    }

    public function testCreateOrReplaceView(): void
    {
        $schema = new Schema();
        $builder = (new PgBuilder())->from('users');
        $result = $schema->createOrReplaceView('all_users', $builder);

        $this->assertStringStartsWith('CREATE OR REPLACE VIEW', $result->query);
    }

    public function testCreateTableWithMultiplePrimaryKeys(): void
    {
        $schema = new Schema();
        $result = $schema->create('order_items', function (Blueprint $table) {
            $table->integer('order_id')->primary();
            $table->integer('product_id')->primary();
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('PRIMARY KEY ("order_id", "product_id")', $result->query);
    }

    public function testCreateTableWithDefaultNull(): void
    {
        $schema = new Schema();
        $result = $schema->create('t', function (Blueprint $table) {
            $table->string('name')->nullable()->default(null);
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('DEFAULT NULL', $result->query);
    }

    public function testAlterAddMultipleColumns(): void
    {
        $schema = new Schema();
        $result = $schema->alter('users', function (Blueprint $table) {
            $table->addColumn('first_name', 'string', 100);
            $table->addColumn('last_name', 'string', 100);
            $table->dropColumn('name');
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('ADD COLUMN "first_name"', $result->query);
        $this->assertStringContainsString('DROP COLUMN "name"', $result->query);
    }

    public function testAlterAddForeignKey(): void
    {
        $schema = new Schema();
        $result = $schema->alter('orders', function (Blueprint $table) {
            $table->addForeignKey('user_id')->references('id')->on('users')->onDelete('CASCADE');
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE', $result->query);
    }

    public function testCreateIndexDefault(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('users', 'idx_email', ['email']);

        $this->assertEquals('CREATE INDEX "idx_email" ON "users" ("email")', $result->query);
    }

    public function testCreateUniqueIndex(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('users', 'idx_email', ['email'], unique: true);

        $this->assertEquals('CREATE UNIQUE INDEX "idx_email" ON "users" ("email")', $result->query);
    }

    public function testCreateIndexMultiColumn(): void
    {
        $schema = new Schema();
        $result = $schema->createIndex('users', 'idx_name', ['first_name', 'last_name']);

        $this->assertEquals('CREATE INDEX "idx_name" ON "users" ("first_name", "last_name")', $result->query);
    }

    public function testAlterRenameColumn(): void
    {
        $schema = new Schema();
        $result = $schema->alter('users', function (Blueprint $table) {
            $table->renameColumn('bio', 'biography');
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('RENAME COLUMN "bio" TO "biography"', $result->query);
    }

    public function testCreateTableWithTimestamps(): void
    {
        $schema = new Schema();
        $result = $schema->create('posts', function (Blueprint $table) {
            $table->id();
            $table->timestamps();
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('"created_at" TIMESTAMP(3)', $result->query);
        $this->assertStringContainsString('"updated_at" TIMESTAMP(3)', $result->query);
    }

    public function testCreateTableWithForeignKey(): void
    {
        $schema = new Schema();
        $result = $schema->create('posts', function (Blueprint $table) {
            $table->id();
            $table->foreignKey('user_id')
                ->references('id')->on('users')
                ->onDelete('CASCADE');
        });
        $this->assertBindingCount($result);

        $this->assertStringContainsString('FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE', $result->query);
    }

    public function testAddForeignKeyStandalone(): void
    {
        $schema = new Schema();
        $result = $schema->addForeignKey('orders', 'fk_user', 'user_id', 'users', 'id', 'CASCADE', 'SET NULL');

        $this->assertEquals(
            'ALTER TABLE "orders" ADD CONSTRAINT "fk_user" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE SET NULL',
            $result->query
        );
    }

    public function testDropTriggerFunction(): void
    {
        $schema = new Schema();

        // dropTrigger should use base SQL dropTrigger
        $result = $schema->dropTrigger('trg_old');

        $this->assertEquals('DROP TRIGGER "trg_old"', $result->query);
    }

    public function testAlterWithUniqueIndex(): void
    {
        $schema = new Schema();
        $result = $schema->alter('users', function (Blueprint $table) {
            $table->addIndex('idx_email', ['email']);
            $table->addIndex('idx_name', ['name']);
        });
        $this->assertBindingCount($result);

        // Both should be standalone CREATE INDEX statements
        $this->assertStringContainsString('CREATE INDEX "idx_email" ON "users" ("email")', $result->query);
        $this->assertStringContainsString('CREATE INDEX "idx_name" ON "users" ("name")', $result->query);
    }

    public function testExactCreateTableWithTypes(): void
    {
        $schema = new Schema();
        $result = $schema->create('accounts', function (Blueprint $table) {
            $table->id();
            $table->string('username', 50);
            $table->boolean('verified');
            $table->json('metadata');
        });

        $this->assertSame(
            'CREATE TABLE "accounts" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "username" VARCHAR(50) NOT NULL, "verified" BOOLEAN NOT NULL, "metadata" JSONB NOT NULL, PRIMARY KEY ("id"))',
            $result->query
        );
        $this->assertEquals([], $result->bindings);
        $this->assertBindingCount($result);
    }

    public function testExactAlterTableAddColumn(): void
    {
        $schema = new Schema();
        $result = $schema->alter('accounts', function (Blueprint $table) {
            $table->addColumn('bio', 'text')->nullable();
        });

        $this->assertSame(
            'ALTER TABLE "accounts" ADD COLUMN "bio" TEXT NULL',
            $result->query
        );
        $this->assertEquals([], $result->bindings);
        $this->assertBindingCount($result);
    }

    public function testExactDropTable(): void
    {
        $schema = new Schema();
        $result = $schema->drop('sessions');

        $this->assertSame('DROP TABLE "sessions"', $result->query);
        $this->assertEquals([], $result->bindings);
        $this->assertBindingCount($result);
    }
}
