<?php

namespace Utopia\Query\Schema;

use Utopia\Query\Builder\BuildResult;
use Utopia\Query\Exception\UnsupportedException;
use Utopia\Query\Exception\ValidationException;

class PostgreSQL extends SQL
{
    protected string $wrapChar = '"';

    protected function compileColumnType(Column $column): string
    {
        return match ($column->type) {
            'string' => 'VARCHAR(' . ($column->length ?? 255) . ')',
            'text' => 'TEXT',
            'integer' => 'INTEGER',
            'bigInteger' => 'BIGINT',
            'float' => 'DOUBLE PRECISION',
            'boolean' => 'BOOLEAN',
            'datetime' => $column->precision ? 'TIMESTAMP(' . $column->precision . ')' : 'TIMESTAMP',
            'timestamp' => $column->precision ? 'TIMESTAMP(' . $column->precision . ') WITHOUT TIME ZONE' : 'TIMESTAMP WITHOUT TIME ZONE',
            'json' => 'JSONB',
            'binary' => 'BYTEA',
            'enum' => 'TEXT',
            'point' => 'GEOMETRY(POINT' . ($column->srid !== null ? ', ' . $column->srid : '') . ')',
            'linestring' => 'GEOMETRY(LINESTRING' . ($column->srid !== null ? ', ' . $column->srid : '') . ')',
            'polygon' => 'GEOMETRY(POLYGON' . ($column->srid !== null ? ', ' . $column->srid : '') . ')',
            'vector' => 'VECTOR(' . ($column->dimensions ?? 0) . ')',
            default => throw new UnsupportedException('Unknown column type: ' . $column->type),
        };
    }

    protected function compileAutoIncrement(): string
    {
        return 'GENERATED BY DEFAULT AS IDENTITY';
    }

    protected function compileUnsigned(): string
    {
        return '';
    }

    protected function compileColumnDefinition(Column $column): string
    {
        $parts = [
            $this->quote($column->name),
            $this->compileColumnType($column),
        ];

        if ($column->isUnsigned) {
            $unsigned = $this->compileUnsigned();
            if ($unsigned !== '') {
                $parts[] = $unsigned;
            }
        }

        if ($column->isAutoIncrement) {
            $parts[] = $this->compileAutoIncrement();
        }

        if (! $column->isNullable) {
            $parts[] = 'NOT NULL';
        } else {
            $parts[] = 'NULL';
        }

        if ($column->hasDefault) {
            $parts[] = 'DEFAULT ' . $this->compileDefaultValue($column->default);
        }

        // PostgreSQL enum emulation via CHECK constraint
        if ($column->type === 'enum' && ! empty($column->enumValues)) {
            $values = \array_map(fn (string $v): string => "'" . \str_replace("'", "''", $v) . "'", $column->enumValues);
            $parts[] = 'CHECK (' . $this->quote($column->name) . ' IN (' . \implode(', ', $values) . '))';
        }

        // No inline COMMENT in PostgreSQL (use COMMENT ON COLUMN separately)

        return \implode(' ', $parts);
    }

    /**
     * @param  string[]  $columns
     */
    public function createIndex(
        string $table,
        string $name,
        array $columns,
        bool $unique = false,
        string $type = '',
        string $method = '',
        string $operatorClass = '',
    ): BuildResult {
        if ($method !== '' && ! \preg_match('/^[A-Za-z0-9_]+$/', $method)) {
            throw new ValidationException('Invalid index method: ' . $method);
        }
        if ($operatorClass !== '' && ! \preg_match('/^[A-Za-z0-9_.]+$/', $operatorClass)) {
            throw new ValidationException('Invalid operator class: ' . $operatorClass);
        }

        $keyword = $unique ? 'CREATE UNIQUE INDEX' : 'CREATE INDEX';

        $sql = $keyword . ' ' . $this->quote($name)
            . ' ON ' . $this->quote($table);

        if ($method !== '') {
            $sql .= ' USING ' . \strtoupper($method);
        }

        $colParts = [];
        foreach ($columns as $c) {
            $part = $this->quote($c);
            if ($operatorClass !== '') {
                $part .= ' ' . $operatorClass;
            }
            $colParts[] = $part;
        }

        $sql .= ' (' . \implode(', ', $colParts) . ')';

        return new BuildResult($sql, []);
    }

    public function dropIndex(string $table, string $name): BuildResult
    {
        return new BuildResult(
            'DROP INDEX ' . $this->quote($name),
            []
        );
    }

    public function dropForeignKey(string $table, string $name): BuildResult
    {
        return new BuildResult(
            'ALTER TABLE ' . $this->quote($table)
            . ' DROP CONSTRAINT ' . $this->quote($name),
            []
        );
    }

    /**
     * @param  list<array{0: string, 1: string, 2: string}>  $params
     */
    public function createProcedure(string $name, array $params, string $body): BuildResult
    {
        $paramList = $this->compileProcedureParams($params);

        $sql = 'CREATE FUNCTION ' . $this->quote($name)
            . '(' . \implode(', ', $paramList) . ')'
            . ' RETURNS VOID LANGUAGE plpgsql AS $$ BEGIN ' . $body . ' END; $$';

        return new BuildResult($sql, []);
    }

    public function dropProcedure(string $name): BuildResult
    {
        return new BuildResult('DROP FUNCTION ' . $this->quote($name), []);
    }

    public function createTrigger(
        string $name,
        string $table,
        string $timing,
        string $event,
        string $body,
    ): BuildResult {
        $timing = \strtoupper($timing);
        $event = \strtoupper($event);

        if (!\in_array($timing, ['BEFORE', 'AFTER', 'INSTEAD OF'], true)) {
            throw new \Utopia\Query\Exception\ValidationException('Invalid trigger timing: ' . $timing);
        }
        if (!\in_array($event, ['INSERT', 'UPDATE', 'DELETE'], true)) {
            throw new \Utopia\Query\Exception\ValidationException('Invalid trigger event: ' . $event);
        }

        $funcName = $name . '_func';

        $sql = 'CREATE FUNCTION ' . $this->quote($funcName)
            . '() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN ' . $body . ' RETURN NEW; END; $$; '
            . 'CREATE TRIGGER ' . $this->quote($name)
            . ' ' . $timing . ' ' . $event
            . ' ON ' . $this->quote($table)
            . ' FOR EACH ROW EXECUTE FUNCTION ' . $this->quote($funcName) . '()';

        return new BuildResult($sql, []);
    }

    /**
     * @param  callable(Blueprint): void  $definition
     */
    public function alter(string $table, callable $definition): BuildResult
    {
        $blueprint = new Blueprint();
        $definition($blueprint);

        $alterations = [];

        foreach ($blueprint->getColumns() as $column) {
            $keyword = $column->isModify ? 'ALTER COLUMN' : 'ADD COLUMN';
            if ($column->isModify) {
                $def = $keyword . ' ' . $this->quote($column->name)
                    . ' TYPE ' . $this->compileColumnType($column);
            } else {
                $def = $keyword . ' ' . $this->compileColumnDefinition($column);
            }
            $alterations[] = $def;
        }

        foreach ($blueprint->getRenameColumns() as $rename) {
            $alterations[] = 'RENAME COLUMN ' . $this->quote($rename['from'])
                . ' TO ' . $this->quote($rename['to']);
        }

        foreach ($blueprint->getDropColumns() as $col) {
            $alterations[] = 'DROP COLUMN ' . $this->quote($col);
        }

        foreach ($blueprint->getForeignKeys() as $fk) {
            $def = 'ADD FOREIGN KEY (' . $this->quote($fk->column) . ')'
                . ' REFERENCES ' . $this->quote($fk->refTable)
                . ' (' . $this->quote($fk->refColumn) . ')';
            if ($fk->onDelete !== '') {
                $def .= ' ON DELETE ' . $fk->onDelete;
            }
            if ($fk->onUpdate !== '') {
                $def .= ' ON UPDATE ' . $fk->onUpdate;
            }
            $alterations[] = $def;
        }

        foreach ($blueprint->getDropForeignKeys() as $name) {
            $alterations[] = 'DROP CONSTRAINT ' . $this->quote($name);
        }

        $statements = [];

        if (! empty($alterations)) {
            $statements[] = 'ALTER TABLE ' . $this->quote($table)
                . ' ' . \implode(', ', $alterations);
        }

        // PostgreSQL indexes are standalone statements, not ALTER TABLE clauses
        foreach ($blueprint->getIndexes() as $index) {
            $cols = \array_map(fn (string $c): string => $this->quote($c), $index->columns);
            $keyword = $index->type === 'unique' ? 'CREATE UNIQUE INDEX' : 'CREATE INDEX';

            $indexSql = $keyword . ' ' . $this->quote($index->name)
                . ' ON ' . $this->quote($table);

            if ($index->method !== '') {
                $indexSql .= ' USING ' . \strtoupper($index->method);
            }

            $colParts = [];
            foreach ($cols as $c) {
                $part = $c;
                if ($index->operatorClass !== '') {
                    $part .= ' ' . $index->operatorClass;
                }
                $colParts[] = $part;
            }

            $indexSql .= ' (' . \implode(', ', $colParts) . ')';
            $statements[] = $indexSql;
        }

        foreach ($blueprint->getDropIndexes() as $name) {
            $statements[] = 'DROP INDEX ' . $this->quote($name);
        }

        return new BuildResult(\implode('; ', $statements), []);
    }

    public function rename(string $from, string $to): BuildResult
    {
        return new BuildResult(
            'ALTER TABLE ' . $this->quote($from) . ' RENAME TO ' . $this->quote($to),
            []
        );
    }

    public function createExtension(string $name): BuildResult
    {
        return new BuildResult('CREATE EXTENSION IF NOT EXISTS ' . $this->quote($name), []);
    }

    public function dropExtension(string $name): BuildResult
    {
        return new BuildResult('DROP EXTENSION IF EXISTS ' . $this->quote($name), []);
    }
}
