<?php

namespace Utopia\Query\Schema;

use Utopia\Query\Builder\BuildResult;
use Utopia\Query\Exception\ValidationException;
use Utopia\Query\Schema\Feature\ColumnComments;
use Utopia\Query\Schema\Feature\CreatePartition;
use Utopia\Query\Schema\Feature\DropPartition;
use Utopia\Query\Schema\Feature\Sequences;
use Utopia\Query\Schema\Feature\TableComments;
use Utopia\Query\Schema\Feature\Types;

class PostgreSQL extends SQL implements Types, Sequences, TableComments, ColumnComments, CreatePartition, DropPartition
{
    protected string $wrapChar = '"';

    protected function compileColumnType(Column $column): string
    {
        return match ($column->type) {
            ColumnType::String, ColumnType::Varchar, ColumnType::Relationship => 'VARCHAR(' . ($column->length ?? 255) . ')',
            ColumnType::Text, ColumnType::MediumText, ColumnType::LongText => 'TEXT',
            ColumnType::Integer => 'INTEGER',
            ColumnType::BigInteger, ColumnType::Id => 'BIGINT',
            ColumnType::Float, ColumnType::Double => 'DOUBLE PRECISION',
            ColumnType::Boolean => 'BOOLEAN',
            ColumnType::Datetime => $column->precision ? 'TIMESTAMP(' . $column->precision . ')' : 'TIMESTAMP',
            ColumnType::Timestamp => $column->precision ? 'TIMESTAMP(' . $column->precision . ') WITHOUT TIME ZONE' : 'TIMESTAMP WITHOUT TIME ZONE',
            ColumnType::Json, ColumnType::Object => 'JSONB',
            ColumnType::Binary => 'BYTEA',
            ColumnType::Enum => 'TEXT',
            ColumnType::Point => 'GEOMETRY(POINT' . ($column->srid !== null ? ', ' . $column->srid : '') . ')',
            ColumnType::Linestring => 'GEOMETRY(LINESTRING' . ($column->srid !== null ? ', ' . $column->srid : '') . ')',
            ColumnType::Polygon => 'GEOMETRY(POLYGON' . ($column->srid !== null ? ', ' . $column->srid : '') . ')',
            ColumnType::Uuid7 => 'VARCHAR(36)',
            ColumnType::Vector => 'VECTOR(' . ($column->dimensions ?? 0) . ')',
        };
    }

    protected function compileAutoIncrement(): string
    {
        return 'GENERATED BY DEFAULT AS IDENTITY';
    }

    protected function compileUnsigned(): string
    {
        return '';
    }

    protected function compileColumnDefinition(Column $column): string
    {
        $parts = [
            $this->quote($column->name),
            $this->compileColumnType($column),
        ];

        if ($column->isUnsigned) {
            $unsigned = $this->compileUnsigned();
            if ($unsigned !== '') {
                $parts[] = $unsigned;
            }
        }

        if ($column->isAutoIncrement) {
            $parts[] = $this->compileAutoIncrement();
        }

        if (! $column->isNullable) {
            $parts[] = 'NOT NULL';
        } else {
            $parts[] = 'NULL';
        }

        if ($column->hasDefault) {
            $parts[] = 'DEFAULT ' . $this->compileDefaultValue($column->default);
        }

        // PostgreSQL enum emulation via CHECK constraint
        if ($column->type === ColumnType::Enum && ! empty($column->enumValues)) {
            $values = \array_map(fn (string $v): string => "'" . \str_replace("'", "''", $v) . "'", $column->enumValues);
            $parts[] = 'CHECK (' . $this->quote($column->name) . ' IN (' . \implode(', ', $values) . '))';
        }

        // No inline COMMENT in PostgreSQL (use COMMENT ON COLUMN separately)

        return \implode(' ', $parts);
    }

    /**
     * @param  string[]  $columns
     * @param  array<string, int>  $lengths
     * @param  array<string, string>  $orders
     * @param  array<string, string>  $collations
     * @param  list<string>  $rawColumns
     */
    public function createIndex(
        string $table,
        string $name,
        array $columns,
        bool $unique = false,
        string $type = '',
        string $method = '',
        string $operatorClass = '',
        array $lengths = [],
        array $orders = [],
        array $collations = [],
        array $rawColumns = [],
        bool $concurrently = false,
    ): BuildResult {
        if ($method !== '' && ! \preg_match('/^[A-Za-z0-9_]+$/', $method)) {
            throw new ValidationException('Invalid index method: ' . $method);
        }
        if ($operatorClass !== '' && ! \preg_match('/^[A-Za-z0-9_.]+$/', $operatorClass)) {
            throw new ValidationException('Invalid operator class: ' . $operatorClass);
        }

        $keyword = $unique ? 'CREATE UNIQUE INDEX' : 'CREATE INDEX';

        if ($concurrently) {
            $keyword .= ' CONCURRENTLY';
        }

        $sql = $keyword . ' ' . $this->quote($name)
            . ' ON ' . $this->quote($table);

        if ($method !== '') {
            $sql .= ' USING ' . \strtoupper($method);
        }

        $indexType = $unique ? IndexType::Unique : ($type !== '' ? IndexType::from($type) : IndexType::Index);
        $index = new Index($name, $columns, $indexType, $lengths, $orders, $method, $operatorClass, $collations, $rawColumns);

        $sql .= ' (' . $this->compileIndexColumns($index) . ')';

        return new BuildResult($sql, []);
    }

    public function dropIndex(string $table, string $name): BuildResult
    {
        return new BuildResult(
            'DROP INDEX ' . $this->quote($name),
            []
        );
    }

    public function dropForeignKey(string $table, string $name): BuildResult
    {
        return new BuildResult(
            'ALTER TABLE ' . $this->quote($table)
            . ' DROP CONSTRAINT ' . $this->quote($name),
            []
        );
    }

    /**
     * @param  list<array{0: ParameterDirection, 1: string, 2: string}>  $params
     */
    public function createProcedure(string $name, array $params, string $body): BuildResult
    {
        $paramList = $this->compileProcedureParams($params);

        $sql = 'CREATE FUNCTION ' . $this->quote($name)
            . '(' . \implode(', ', $paramList) . ')'
            . ' RETURNS VOID LANGUAGE plpgsql AS $$ BEGIN ' . $body . ' END; $$';

        return new BuildResult($sql, []);
    }

    public function dropProcedure(string $name): BuildResult
    {
        return new BuildResult('DROP FUNCTION ' . $this->quote($name), []);
    }

    public function createTrigger(
        string $name,
        string $table,
        TriggerTiming $timing,
        TriggerEvent $event,
        string $body,
    ): BuildResult {
        $funcName = $name . '_func';

        $sql = 'CREATE FUNCTION ' . $this->quote($funcName)
            . '() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN ' . $body . ' RETURN NEW; END; $$; '
            . 'CREATE TRIGGER ' . $this->quote($name)
            . ' ' . $timing->value . ' ' . $event->value
            . ' ON ' . $this->quote($table)
            . ' FOR EACH ROW EXECUTE FUNCTION ' . $this->quote($funcName) . '()';

        return new BuildResult($sql, []);
    }

    /**
     * @param  callable(Blueprint): void  $definition
     */
    public function alter(string $table, callable $definition): BuildResult
    {
        $blueprint = new Blueprint();
        $definition($blueprint);

        $alterations = [];

        foreach ($blueprint->columns as $column) {
            $keyword = $column->isModify ? 'ALTER COLUMN' : 'ADD COLUMN';
            if ($column->isModify) {
                $def = $keyword . ' ' . $this->quote($column->name)
                    . ' TYPE ' . $this->compileColumnType($column);
            } else {
                $def = $keyword . ' ' . $this->compileColumnDefinition($column);
            }
            $alterations[] = $def;
        }

        foreach ($blueprint->renameColumns as $rename) {
            $alterations[] = 'RENAME COLUMN ' . $this->quote($rename->from)
                . ' TO ' . $this->quote($rename->to);
        }

        foreach ($blueprint->dropColumns as $col) {
            $alterations[] = 'DROP COLUMN ' . $this->quote($col);
        }

        foreach ($blueprint->foreignKeys as $fk) {
            $def = 'ADD FOREIGN KEY (' . $this->quote($fk->column) . ')'
                . ' REFERENCES ' . $this->quote($fk->refTable)
                . ' (' . $this->quote($fk->refColumn) . ')';
            if ($fk->onDelete !== null) {
                $def .= ' ON DELETE ' . $fk->onDelete->toSql();
            }
            if ($fk->onUpdate !== null) {
                $def .= ' ON UPDATE ' . $fk->onUpdate->toSql();
            }
            $alterations[] = $def;
        }

        foreach ($blueprint->dropForeignKeys as $name) {
            $alterations[] = 'DROP CONSTRAINT ' . $this->quote($name);
        }

        $statements = [];

        if (! empty($alterations)) {
            $statements[] = 'ALTER TABLE ' . $this->quote($table)
                . ' ' . \implode(', ', $alterations);
        }

        // PostgreSQL indexes are standalone statements, not ALTER TABLE clauses
        foreach ($blueprint->indexes as $index) {
            $keyword = $index->type === IndexType::Unique ? 'CREATE UNIQUE INDEX' : 'CREATE INDEX';

            $indexSql = $keyword . ' ' . $this->quote($index->name)
                . ' ON ' . $this->quote($table);

            if ($index->method !== '') {
                $indexSql .= ' USING ' . \strtoupper($index->method);
            }

            $indexSql .= ' (' . $this->compileIndexColumns($index) . ')';
            $statements[] = $indexSql;
        }

        foreach ($blueprint->dropIndexes as $name) {
            $statements[] = 'DROP INDEX ' . $this->quote($name);
        }

        return new BuildResult(\implode('; ', $statements), []);
    }

    public function rename(string $from, string $to): BuildResult
    {
        return new BuildResult(
            'ALTER TABLE ' . $this->quote($from) . ' RENAME TO ' . $this->quote($to),
            []
        );
    }

    public function createExtension(string $name): BuildResult
    {
        return new BuildResult('CREATE EXTENSION IF NOT EXISTS ' . $this->quote($name), []);
    }

    public function dropExtension(string $name): BuildResult
    {
        return new BuildResult('DROP EXTENSION IF EXISTS ' . $this->quote($name), []);
    }

    /**
     * Create a collation.
     *
     * @param  array<string, string>  $options  Key-value pairs (e.g. ['provider' => 'icu', 'locale' => 'und-u-ks-level1'])
     */
    public function createCollation(string $name, array $options, bool $deterministic = true): BuildResult
    {
        $optParts = [];
        foreach ($options as $key => $value) {
            $optParts[] = $key . " = '" . \str_replace("'", "''", $value) . "'";
        }
        $optParts[] = 'deterministic = ' . ($deterministic ? 'true' : 'false');

        $sql = 'CREATE COLLATION IF NOT EXISTS ' . $this->quote($name)
            . ' (' . \implode(', ', $optParts) . ')';

        return new BuildResult($sql, []);
    }

    public function renameIndex(string $table, string $from, string $to): BuildResult
    {
        return new BuildResult(
            'ALTER INDEX ' . $this->quote($from) . ' RENAME TO ' . $this->quote($to),
            []
        );
    }

    /**
     * PostgreSQL uses schemas instead of databases for namespace isolation.
     */
    public function createDatabase(string $name): BuildResult
    {
        return new BuildResult('CREATE SCHEMA ' . $this->quote($name), []);
    }

    public function dropDatabase(string $name): BuildResult
    {
        return new BuildResult('DROP SCHEMA IF EXISTS ' . $this->quote($name) . ' CASCADE', []);
    }

    public function analyzeTable(string $table): BuildResult
    {
        return new BuildResult('ANALYZE ' . $this->quote($table), []);
    }

    /**
     * Alter a column's type with an optional USING expression for type casting.
     */
    public function alterColumnType(string $table, string $column, string $type, string $using = ''): BuildResult
    {
        $sql = 'ALTER TABLE ' . $this->quote($table)
            . ' ALTER COLUMN ' . $this->quote($column)
            . ' TYPE ' . $type;

        if ($using !== '') {
            $sql .= ' USING ' . $using;
        }

        return new BuildResult($sql, []);
    }

    public function dropIndexConcurrently(string $name): BuildResult
    {
        return new BuildResult('DROP INDEX CONCURRENTLY ' . $this->quote($name), []);
    }

    public function createType(string $name, array $values): BuildResult
    {
        $escaped = array_map(fn (string $v): string => "'" . str_replace("'", "''", $v) . "'", $values);

        return new BuildResult(
            'CREATE TYPE ' . $this->quote($name) . ' AS ENUM (' . implode(', ', $escaped) . ')',
            []
        );
    }

    public function dropType(string $name): BuildResult
    {
        return new BuildResult('DROP TYPE ' . $this->quote($name), []);
    }

    public function createSequence(string $name, int $start = 1, int $incrementBy = 1): BuildResult
    {
        return new BuildResult(
            'CREATE SEQUENCE ' . $this->quote($name) . ' START ' . $start . ' INCREMENT BY ' . $incrementBy,
            []
        );
    }

    public function dropSequence(string $name): BuildResult
    {
        return new BuildResult('DROP SEQUENCE ' . $this->quote($name), []);
    }

    public function nextVal(string $name): BuildResult
    {
        return new BuildResult(
            "SELECT nextval('" . str_replace("'", "''", $name) . "')",
            []
        );
    }

    public function commentOnTable(string $table, string $comment): BuildResult
    {
        return new BuildResult(
            'COMMENT ON TABLE ' . $this->quote($table) . " IS '" . str_replace("'", "''", $comment) . "'",
            []
        );
    }

    public function commentOnColumn(string $table, string $column, string $comment): BuildResult
    {
        return new BuildResult(
            'COMMENT ON COLUMN ' . $this->quote($table) . '.' . $this->quote($column) . " IS '" . str_replace("'", "''", $comment) . "'",
            []
        );
    }

    public function createPartition(string $parent, string $name, string $expression): BuildResult
    {
        return new BuildResult(
            'CREATE TABLE ' . $this->quote($name) . ' PARTITION OF ' . $this->quote($parent) . ' FOR VALUES ' . $expression,
            []
        );
    }

    public function dropPartition(string $table, string $name): BuildResult
    {
        return new BuildResult(
            'DROP TABLE ' . $this->quote($name),
            []
        );
    }
}
